In [16]:
# importer les données depuis le document excel «utilisateurs»

import numpy as np
import pandas as pd

util_df = pd.read_excel("./utilisateurs.xlsx")

util_df.drop(['TYPE', 'relecteur'], axis=1, inplace=True)
util_df['email2'] = 'undefined'

print(util_df.isna().apply(sum))
# > aucune valeur de manque

ids = util_df.groupby('id').count().sort_values('nom', ascending=False)
# print(ids)
# > Les identifiants sont bien tous uniques

nprof = util_df.groupby('profession').count().sort_values('nom', ascending=False)
# print(nprof)
# > créer une table des professions avec 5 entrée

nvil = util_df.loc[:,['ville', 'nom']].groupby('ville').count().sort_values('nom', ascending=False)
# print(nvil)
# > 505 villes

npays = util_df.loc[:,['pays', 'nom']].groupby('pays').count().sort_values('nom', ascending=False)
# print(npays)
# > 240 Pays différents

ngenr = util_df.loc[:,['genre', 'nom']].groupby('genre').count().sort_values('nom', ascending=False)
# print(ngenr)
# > 3 genres

id            0
prenom        0
nom           0
email2        0
profession    0
ville         0
pays          0
genre         0
type          0
dtype: int64

In [78]:
# Objectif : vérifier que les villes sont bien toutes associées avec le même pays

# générer un tableau d’occurences de chaque villes
nvil.reset_index(inplace=True)
nvil.columns = ['ville', 'n']
# on ne garde que celles qui apparaissent plus d’une fois
nvil = nvil[nvil["n"] > 1]

# affichage des pays correspondant en fonction des villes
for i in range(nvil.shape[0]) :
    payvil = util_df[util_df['ville'] == nvil['ville'][i]]
    print(payvil.loc[:,['ville', 'pays']])
# > On peut voir que les pays et les villes n’ont rien à voir dans nos données

      ville                   pays
40   Tabriz  Saint Kitts and Nevis
159  Tabriz                Burundi
196  Tabriz            El Salvador
558  Tabriz               Dominica
727  Tabriz                  Sudan
870  Tabriz                   Iraq
955  Tabriz              Venezuela
          ville                                    pays
48   Phnom Penh  Korea, Democratic People"S Republic of
303  Phnom Penh                                 Myanmar
330  Phnom Penh                                 Senegal
391  Phnom Penh                          Cayman Islands
719  Phnom Penh                                 Bermuda
888  Phnom Penh                                  Monaco
      ville                              pays
233  Boston                           Tunisia
471  Boston  Lao People"S Democratic Republic
619  Boston                           AndorrA
717  Boston                           Bahrain
767  Boston                Russian Federation
920  Boston                           Lesotho
        ville                     pays
216  Montreal  Virgin Islands, British
224  Montreal                   Jersey
372  Montreal                  Mayotte
606  Montreal                   Latvia
787  Montreal                    China
      ville            pays
188  Multan          Canada
281  Multan         Belarus
425  Multan       Indonesia
480  Multan           Ghana
696  Multan  Western Sahara
      ville                         pays
360  Manaus                       Sweden
536  Manaus      Virgin Islands, British
694  Manaus                       RWANDA
887  Manaus  French Southern Territories
990  Manaus                        Gabon
         ville     pays
29   Pago Pago  Ukraine
567  Pago Pago  Austria
603  Pago Pago   Gambia
679  Pago Pago  Senegal
730  Pago Pago  Nigeria
        ville         pays
57   Toulouse   Costa Rica
346  Toulouse  Puerto Rico
587  Toulouse    Swaziland
765  Toulouse      Bahrain
940  Toulouse        Italy
        ville                              pays
158  Srinagar  Lao People"S Democratic Republic
201  Srinagar                        Kyrgyzstan
351  Srinagar                             Aruba
844  Srinagar                          Portugal
951  Srinagar                          Botswana
     ville                     pays
277  Ambon           Western Sahara
403  Ambon  Virgin Islands, British
552  Ambon                 Cambodia
714  Ambon            New Caledonia
864  Ambon                    Niger
         ville                  pays
21   Edinburgh  Syrian Arab Republic
302  Edinburgh               Reunion
448  Edinburgh                 Japan
636  Edinburgh             Argentina
766  Edinburgh                 China
      ville                                  pays
5    Avarua                               AndorrA
424  Avarua                               Nigeria
439  Avarua  United States Minor Outlying Islands
825  Avarua                                  Iraq
894  Avarua                                  Mali
       ville     pays
174  Chicago    Samoa
206  Chicago  Belgium
534  Chicago  Belarus
631  Chicago    Niger
900  Chicago   Guinea
            ville            pays
101  Indianapolis      Costa Rica
179  Indianapolis        Pitcairn
413  Indianapolis  American Samoa
588  Indianapolis          Jersey
916  Indianapolis     Puerto Rico
       ville     pays
38   Dunedin  Eritrea
436  Dunedin  Georgia
476  Dunedin     Oman
715  Dunedin   Panama
     ville                          pays
189  Surat                American Samoa
524  Surat                      Djibouti
632  Surat                      Bulgaria
661  Surat  Tanzania, United Republic of
         ville                       pays
305  Gaziantep                   Mongolia
529  Gaziantep  Saint Pierre and Miquelon
846  Gaziantep                      Macao
926  Gaziantep                     Israel
      ville                  pays
14   Odessa                Uganda
379  Odessa               Iceland
520  Odessa         New Caledonia
754  Odessa  United Arab Emirates
           ville                            pays
308  Cork (city)                          Mexico
624  Cork (city)  British Indian Ocean Territory
645  Cork (city)                            Peru
875  Cork (city)          Libyan Arab Jamahiriya
        ville                      pays
83   Surabaya                  Anguilla
192  Surabaya                  Bulgaria
229  Surabaya             Faroe Islands
458  Surabaya  Turks and Caicos Islands
                   ville                      pays
82   Bandar Seri Begawan               El Salvador
301  Bandar Seri Begawan  Turks and Caicos Islands
861  Bandar Seri Begawan                      Chad
969  Bandar Seri Begawan                   Belgium
     ville                             pays
142  Dhaka                       Guadeloupe
292  Dhaka  Palestinian Territory, Occupied
768  Dhaka                          Tokelau
903  Dhaka                           Uganda
               ville                   pays
422  Nizhny Novgorod          Cote D"Ivoire
942  Nizhny Novgorod                  Samoa
975  Nizhny Novgorod  Serbia and Montenegro
996  Nizhny Novgorod                 Canada
     ville                                          pays
312  Busan  South Georgia and the South Sandwich Islands
347  Busan                              Christmas Island
459  Busan                                        Tuvalu
869  Busan                         Sao Tome and Principe
    ville       pays
1    Suva   Djibouti
33   Suva   Guernsey
133  Suva     Bhutan
167  Suva  Nicaragua
            ville            pays
792  Punta Arenas  Norfolk Island
798  Punta Arenas           Nepal
845  Punta Arenas      Tajikistan
906  Punta Arenas          Jersey
          ville           pays
153  Montevideo  Bouvet Island
276  Montevideo        Senegal
463  Montevideo         Uganda
911  Montevideo        Bahrain
      ville                    pays
99   Dammam             Netherlands
180  Dammam           Faroe Islands
596  Dammam  Libyan Arab Jamahiriya
750  Dammam        French Polynesia
     ville                   pays
91   Macau  Sao Tome and Principe
387  Macau  Sao Tome and Principe
568  Macau               Barbados
796  Macau                Albania
      ville            pays
88   Nassau          Gambia
334  Nassau  Western Sahara
758  Nassau         AndorrA
865  Nassau         Belgium
          ville              pays
264  Washington     French Guiana
331  Washington  Christmas Island
678  Washington            Jordan
812  Washington         Greenland
         ville          pays
328  Rotterdam  Saint Helena
337  Rotterdam   Philippines
551  Rotterdam        Greece
759  Rotterdam        Jordan
       ville                      pays
286  Taiyuan               Netherlands
658  Taiyuan                  Portugal
699  Taiyuan  Northern Mariana Islands
917  Taiyuan                     Malta
      ville           pays
81   Durban  Guinea-Bissau
170  Durban        Romania
212  Durban  Bouvet Island
353  Durban        Grenada
    ville              pays
143  Linz  Marshall Islands
151  Linz           Tunisia
457  Linz       Netherlands
858  Linz            RWANDA
     ville                       pays
220  Tunis          Wallis and Futuna
488  Tunis                    Ukraine
572  Tunis                  Nicaragua
785  Tunis  Saint Pierre and Miquelon
      ville            pays
256  Samara      Costa Rica
783  Samara  American Samoa
818  Samara      Azerbaijan
965  Samara         Uruguay
             ville                         pays
307  Port of Spain                       Belize
743  Port of Spain                        Niger
834  Port of Spain                      Finland
962  Port of Spain  French Southern Territories
     ville                  pays
7    Medan  Virgin Islands, U.S.
485  Medan            Kyrgyzstan
860  Medan                Guyana
932  Medan             Sri Lanka
           ville        pays
86   Addis Ababa   Lithuania
141  Addis Ababa      Cyprus
237  Addis Ababa        Peru
614  Addis Ababa  Costa Rica
         ville               pays
430  Jamestown  Brunei Darussalam
711  Jamestown              Gabon
720  Jamestown              Malta
893  Jamestown       Saint Helena
         ville               pays
45   Ahmedabad           Dominica
336  Ahmedabad          Hong Kong
584  Ahmedabad  Equatorial Guinea
839  Ahmedabad            Nigeria
           ville                   pays
53   Albuquerque               Viet Nam
258  Albuquerque  Serbia and Montenegro
325  Albuquerque              Sri Lanka
961  Albuquerque                  Nauru
      ville           pays
200  Yangon        Tokelau
226  Yangon         Malawi
704  Yangon  Faroe Islands
998  Yangon        Namibia
      ville               pays
157  Ankara               Togo
407  Ankara  Equatorial Guinea
503  Ankara      Åland Islands
988  Ankara           Djibouti
           ville                                   pays
590  Minneapolis         British Indian Ocean Territory
963  Minneapolis                             Costa Rica
986  Minneapolis                               Mongolia
989  Minneapolis  Congo, The Democratic Republic of the
        ville                              pays
291  Santiago                         Argentina
487  Santiago                            Mexico
737  Santiago  Saint Vincent and the Grenadines
952  Santiago                        Montserrat
        ville                  pays
612  San José                Cyprus
615  San José               Jamaica
899  San José              Pitcairn
999  San José  Syrian Arab Republic
         ville                pays
235  Guangzhou             Denmark
470  Guangzhou           Mauritius
664  Guangzhou             Ukraine
919  Guangzhou  Russian Federation
    ville          pays
513  Apia  Cook Islands
627  Apia         India
676  Apia        Monaco
804  Apia        Brazil
       ville      pays
147  Caracas    Israel
339  Caracas   Romania
359  Caracas  Slovakia
837  Caracas      Peru
          ville                                        pays
399  Gothenburg                                        Chad
682  Gothenburg  Macedonia, The Former Yugoslav Republic of
690  Gothenburg                                     Uruguay
744  Gothenburg                      Bosnia and Herzegovina
     ville                   pays
31   Seoul  Serbia and Montenegro
423  Seoul            Saint Lucia
863  Seoul                  Egypt
    ville            pays
268  Rome  Czech Republic
519  Rome        Dominica
808  Rome          Sweden
         ville            pays
329  Road Town         Belarus
362  Road Town  Western Sahara
553  Road Town         Mayotte
      ville        pays
491  Malabo    Slovenia
677  Malabo       Italy
980  Malabo  Seychelles
               ville                       pays
241  City of Halifax                      Samoa
569  City of Halifax                  Gibraltar
733  City of Halifax  Saint Pierre and Miquelon
      ville                                        pays
12   Riyadh      Korea, Democratic People"S Republic of
611  Riyadh  Macedonia, The Former Yugoslav Republic of
687  Riyadh                                   Venezuela
                  ville         pays
234  City of San Marino     Viet Nam
654  City of San Marino  Netherlands
811  City of San Marino       Mexico
       ville                     pays
120  Da Nang                     Fiji
482  Da Nang                    China
753  Da Nang  Cocos (Keeling) Islands
         ville                                          pays
364  Riverside                          United Arab Emirates
502  Riverside  South Georgia and the South Sandwich Islands
629  Riverside                                          Iraq
       ville      pays
41   Córdoba  Pitcairn
222  Córdoba   Austria
827  Córdoba     Italy
    ville     pays
428  Malé  Grenada
761  Malé    Qatar
816  Malé    Macao
     ville            pays
208  Thiès       Sri Lanka
774  Thiès  Western Sahara
791  Thiès         Reunion
       ville         pays
35   Thimphu        Niger
601  Thimphu  Philippines
802  Thimphu       Uganda
          ville        pays
195  Davao City  Mozambique
365  Davao City       Egypt
618  Davao City        Togo
        ville      pays
187  Makassar  Djibouti
505  Makassar  Colombia
853  Makassar    Poland
      ville                                        pays
42   Aarhus                        Netherlands Antilles
110  Aarhus  Macedonia, The Former Yugoslav Republic of
284  Aarhus                        Moldova, Republic of
      ville                 pays
309  Majuro             Bulgaria
355  Majuro        Faroe Islands
831  Majuro  Trinidad and Tobago
    ville                     pays
420  Graz                  Ecuador
689  Graz  Virgin Islands, British
708  Graz                 Bulgaria
        ville          pays
161  Semarang  Burkina Faso
537  Semarang        Cyprus
856  Semarang      Zimbabwe
       ville                              pays
369  Jakarta  Lao People"S Democratic Republic
691  Jakarta                         Indonesia
731  Jakarta                           Estonia
       ville         pays
124  Incheon  Puerto Rico
274  Incheon      Hungary
418  Incheon        Sudan
       ville                            pays
46   Seattle  British Indian Ocean Territory
271  Seattle          Svalbard and Jan Mayen
477  Seattle                      Kazakhstan
      ville            pays
561  Ibadan         Myanmar
591  Ibadan        Thailand
788  Ibadan  Western Sahara
      ville      pays
443  Juneau     Malta
509  Juneau  Thailand
707  Juneau   Mayotte
     ville                         pays
115  Sofia                    Argentina
227  Sofia                         Mali
386  Sofia  Falkland Islands (Malvinas)
        ville                    pays
129  Helsinki                 Croatia
673  Helsinki  Libyan Arab Jamahiriya
756  Helsinki                   Macao
       ville                             pays
504  Stanley  Palestinian Territory, Occupied
628  Stanley                      Afghanistan
974  Stanley                           Uganda
         ville                  pays
19   Koulikoro            Madagascar
322  Koulikoro                  Niue
466  Koulikoro  Virgin Islands, U.S.
            ville                  pays
444  Kuala Lumpur              Maldives
613  Kuala Lumpur               Vanuatu
751  Kuala Lumpur  Moldova, Republic of
           ville                                   pays
721  Guadalajara                            Isle of Man
852  Guadalajara  Congo, The Democratic Republic of the
960  Guadalajara                               Cambodia
           ville       pays
175  San Antonio    Nigeria
683  San Antonio   Slovakia
705  San Antonio  Mauritius
       ville                      pays
564  Tampere  Central African Republic
675  Tampere                  Maldives
725  Tampere         Wallis and Futuna
           ville        pays
338  George Town       Macao
417  George Town        Guam
780  George Town  Mozambique
       ville      pays
164  Lanzhou  Maldives
223  Lanzhou    Greece
872  Lanzhou   Bolivia
        ville                       pays
249  Funafuti                  Argentina
539  Funafuti                      Tonga
984  Funafuti  Taiwan, Province of China
        ville          pays
122  Freetown      Guernsey
176  Freetown  Sierra Leone
538  Freetown     Sri Lanka
         ville        pays
119  Frankfurt   Lithuania
797  Frankfurt    Dominica
814  Frankfurt  Azerbaijan
       ville                            pays
108  Tijuana                          Turkey
173  Tijuana  British Indian Ocean Territory
348  Tijuana                French Polynesia
          ville                      pays
579  Louisville               El Salvador
640  Louisville                  Anguilla
976  Louisville  Turks and Caicos Islands
      ville                          pays
193  Luanda      Turks and Caicos Islands
320  Luanda                       AndorrA
934  Luanda  Tanzania, United Republic of
         ville          pays
294  Abu Dhabi  Saint Helena
435  Abu Dhabi      Cambodia
635  Abu Dhabi      Djibouti
      ville                      pays
246  Dublin  Turks and Caicos Islands
771  Dublin      Virgin Islands, U.S.
910  Dublin                    Gambia
      ville         pays
288  Douala       Latvia
755  Douala  New Zealand
907  Douala   Luxembourg
                ville                       pays
250  Saint Petersburg                    Georgia
574  Saint Petersburg    Virgin Islands, British
937  Saint Petersburg  Taiwan, Province of China
       ville                            pays
213  Tianjin                         Bolivia
415  Tianjin                     El Salvador
842  Tianjin  British Indian Ocean Territory
        ville        pays
578  Istanbul   Gibraltar
586  Istanbul    Barbados
836  Istanbul  Montserrat
         ville                  pays
182  Barcelona                Turkey
186  Barcelona  Syrian Arab Republic
452  Barcelona               Hungary
        ville               pays
113  Mata-Utu             Tuvalu
146  Mata-Utu  Equatorial Guinea
410  Mata-Utu            Vanuatu
      ville        pays
306  Xining    Kiribati
746  Xining  Antarctica
832  Xining      Malawi
        ville                       pays
77   Valletta  Iran, Islamic Republic Of
267  Valletta                      Nepal
655  Valletta                Puerto Rico
         ville           pays
203  Pyongyang  Guinea-Bissau
287  Pyongyang        Eritrea
357  Pyongyang       Colombia
      ville                          pays
221  Bissau           Antigua and Barbuda
380  Bissau  Tanzania, United Republic of
392  Bissau                       Algeria
            ville                  pays
913  Bloemfontein  Netherlands Antilles
927  Bloemfontein          Turkmenistan
995  Bloemfontein                Gambia
         ville          pays
131  Port Said  Saint Helena
280  Port Said    Bangladesh
840  Port Said        France
           ville                pays
475  Quezon City  Dominican Republic
723  Quezon City             Namibia
728  Quezon City               Nepal
      ville            pays
197  Nagoya        Mongolia
495  Nagoya  American Samoa
617  Nagoya   French Guiana
       ville           pays
239  Beijing        Denmark
361  Beijing   South Africa
764  Beijing  Faroe Islands
       ville                     pays
412  Papeete                 Guernsey
507  Papeete  Cocos (Keeling) Islands
672  Papeete                  Romania
        ville        pays
242  Pretoria     Bolivia
530  Pretoria  Uzbekistan
843  Pretoria       Samoa
      ville                  pays
431  Muscat               Burundi
525  Muscat              Cambodia
688  Muscat  United Arab Emirates
       ville                            pays
493  Yaoundé  British Indian Ocean Territory
854  Yaoundé                        Bulgaria
909  Yaoundé                         Bahrain
         ville           pays
52   Bucharest  Faroe Islands
697  Bucharest         Belize
801  Bucharest       Bulgaria
      ville        pays
20   Munich     Ecuador
98   Munich  Azerbaijan
656  Munich    Cameroon
     ville                              pays
366  Minsk             Saint Kitts and Nevis
473  Minsk                           Croatia
541  Minsk  Lao People"S Democratic Republic
          ville                      pays
607  Porto-Novo  Northern Mariana Islands
939  Porto-Novo                     Congo
979  Porto-Novo          Christmas Island
      ville           pays
105  Zürich  Åland Islands
356  Zürich         Guyana
390  Zürich  New Caledonia
       ville                                    pays
11   Baghdad  Korea, Democratic People"S Republic of
205  Baghdad                                    Peru
724  Baghdad                 Cocos (Keeling) Islands
         ville            pays
252  Charlotte  Czech Republic
261  Charlotte        Botswana
987  Charlotte          Turkey
           ville                    pays
17   Mexico City  Bosnia and Herzegovina
238  Mexico City              Antarctica

In [74]:
# combien de pays différents ?

(1) , (2) , (3)